### PR TITLE
Update benchmarks setup for DCISolver.jl

### PR DESCRIPTION
**Pull request by MonssafToukal**
This PR's  purpose is to test the benchmarks from a PR coming from an outsider of the JSO organization.

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot  runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Review by tmigot — CHANGES_REQUESTED** [review]
Can you undo the commit modifying the readme? The rest looks good to me. Congrats!

**Review by tmigot — APPROVED** [review]

**Pull request merged**
