### PR TITLE
Update DCISolver for Krylov 0.8

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by tmigot** [comment]
I believe the doc fails because also uses `JSOSolvers`, https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/pull/115

**Comment by tmigot** [comment]
I believe the doc fails because also uses `JSOSolvers`, https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/pull/115

**Comment by tmigot** [comment]
Can you update also the `Project.toml` in the docs.

**Comment by tmigot** [comment]
the doc is failing because of CaNNOLeS now... https://github.com/JuliaSmoothOptimizers/CaNNOLeS.jl/pull/45

**Comment by amontoison** [comment]
You can do a new release @tmigot :+1:

**Pull request merged**
